# Generated by Django 4.2.11 on 2026-03-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('step_1', 'Step 1 - Personal Info'), ('step_2', 'Step 2 - ID Proof'), ('step_3', 'Step 3 - Address Proof'), ('step_4', 'Step 4 - Employment Proof'), ('step_5', 'Step 5 - References'), ('step_6', 'Step 6 - Review'), ('step_7', 'Step 7 - Final'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('personal_info', models.JSONField(blank=True, default=dict)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='tenant_docs/id_proofs/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='tenant_docs/address_proofs/')),
                ('employment_proof', models.FileField(blank=True, null=True, upload_to='tenant_docs/employment_proofs/')),
                ('references', models.JSONField(blank=True, default=list)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_requests', to='properties.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
