# Generated by Django 4.2.11 on 2026-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('step1', 'Step 1 - Basic Info'), ('step2', 'Step 2 - Identity Verification'), ('step3', 'Step 3 - Employment Details'), ('step4', 'Step 4 - Emergency Contact'), ('step5', 'Step 5 - Previous Rental History'), ('step6', 'Step 6 - Document Upload'), ('step7', 'Step 7 - Agreement & Submission'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='step1', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('num_occupants', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='onboarding_docs/')),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='onboarding_docs/')),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_relation', models.CharField(blank=True, max_length=50)),
                ('previous_address', models.TextField(blank=True)),
                ('previous_landlord', models.CharField(blank=True, max_length=200)),
                ('previous_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255)),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='onboarding_docs/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
