# Generated by Django 4.2.11 on 2026-03-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantonboardingrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantonboardingrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_requests', to='properties.room'),
        ),
        migrations.AddField(
            model_name='tenantonboardingrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
