# Generated by Django 4.2.11 on 2026-03-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building_type', models.CharField(choices=[('apartment', 'Apartment Complex'), ('house', 'Individual House'), ('villa', 'Villa'), ('commercial', 'Commercial Building'), ('pg', 'PG/Hostel')], default='apartment', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('studio', 'Studio'), ('single', 'Single Room'), ('double', 'Double Room'), ('shop', 'Shop/Office')], max_length=20)),
                ('floor_number', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.building')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.room')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='building_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.building')),
            ],
        ),
    ]
