# Generated by Django 4.2.11 on 2026-03-19 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantreview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingreview',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.building'),
        ),
        migrations.AddField(
            model_name='buildingreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='buildingreview',
            unique_together={('building', 'tenant')},
        ),
    ]
