# Generated by Django 4.2.11 on 2026-03-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_tenant_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tenant_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingreview',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.building'),
        ),
        migrations.AddField(
            model_name='buildingreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tenantreview',
            unique_together={('reviewer', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='buildingreview',
            unique_together={('reviewer', 'building')},
        ),
    ]
