# Generated by Django 4.2.11 on 2026-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='lease_agreements/')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('move_in_condition', models.TextField(blank=True)),
                ('move_out_condition', models.TextField(blank=True)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('owner_signed', models.BooleanField(default=False)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
